<?php
$pets = [
  [
    'ID' => 'HPH-A-001',
    'name' => 'Max',
    'breed' => 'Golden Retriever',
    'gender' => 'male',
    'color' => 'golden',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 3,
    'type' => 'Dog',
    'image' => 'assets/images/adopt3.jpeg',
    'image2' => 'assets/images/dog2.jpeg',
    'image3' => 'assets/images/dog3.jpeg'
  ],
  [
    'ID' => 'HPH-A-002',
    'name' => 'Luna',
    'breed' => 'Siamese',
    'gender' => 'female',
    'color' => 'white',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 4,
    'type' => 'Cat',
    'image' => 'assets/images/adopt2.jpeg',
    'image2' => 'assets/images/cat2.jpeg',
    'image3' => 'assets/images/cat3.jpeg'
  ],
  [
    'ID' => 'HPH-A-003',
    'name' => 'Rocky',
    'breed' => 'Bulldog',
    'gender' => 'male',
    'color' => 'brindle',
    'vaccinated' => 'no',
    'dewormed' => 'yes',
    'age' => 2,
    'type' => 'Dog',
    'image' => 'assets/images/adopt3.jpeg',
    'image2' => 'assets/images/dog2.jpeg',
    'image3' => 'assets/images/dog3.jpeg'
  ],
  [
    'ID' => 'HPH-A-004',
    'name' => 'Bella',
    'breed' => 'Persian',
    'gender' => 'female',
    'color' => 'grey',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 3,
    'type' => 'Cat',
    'image' => 'assets/images/adopt2.jpeg',
    'image2' => 'assets/images/cat2.jpeg',
    'image3' => 'assets/images/cat3.jpeg'
  ],
  [
    'ID' => 'HPH-A-005',
    'name' => 'Charlie',
    'breed' => 'Beagle',
    'gender' => 'male',
    'color' => 'tricolor',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 5,
    'type' => 'Rabbit',
    'image' => 'assets/images/adopt5.jpeg',
    'image2' => 'assets/images/rabbit2.jpeg',
    'image3' => 'assets/images/rabbit3.jpeg'
  ],
  [
    'ID' => 'HPH-A-006',
    'name' => 'Daisy',
    'breed' => 'Maine Coon',
    'gender' => 'female',
    'color' => 'brown',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 2,
    'type' => 'Cat',
    'image' => 'assets/images/adopt2.jpeg',
    'image2' => 'assets/images/cat2.jpeg',
    'image3' => 'assets/images/cat3.jpeg'
  ],
  [
    'ID' => 'HPH-A-007',
    'name' => 'Jack',
    'breed' => 'Husky',
    'gender' => 'male',
    'color' => 'black and white',
    'vaccinated' => 'no',
    'dewormed' => 'yes',
    'age' => 1,
    'type' => 'Dog',
    'image' => 'assets/images/adopt3.jpeg',
    'image2' => 'assets/images/dog2.jpeg',
    'image3' => 'assets/images/dog3.jpeg'
  ],
  [
    'ID' => 'HPH-A-008',
    'name' => 'Chloe',
    'breed' => 'Ragdoll',
    'gender' => 'female',
    'color' => 'cream',
    'vaccinated' => 'yes',
    'dewormed' => 'yes',
    'age' => 4,
    'type' => 'Cat',
    'image' => 'assets/images/adopt2.jpeg',
    'image2' => 'assets/images/cat2.jpeg',
    'image3' => 'assets/images/cat3.jpeg'
  ],
  [
    'ID' => 'HPH-A-009',
    'name' => 'Cooper',
    'breed' => 'Labrador Retriever',
    'gender' => 'male',
    'color' => 'black',
    'vaccinated' => 'yes',
    'dewormed' => 'no',
    'age' => 6,
    'type' => 'Dog',
    'image' => 'assets/images/adopt3.jpeg',
    'image2' => 'assets/images/dog2.jpeg',
    'image3' => 'assets/images/dog3.jpeg'
  ],
  [
    'ID' => 'HPH-A-010',
    'name' => 'Molly',
    'breed' => 'Bengal',
    'gender' => 'female',
    'color' => 'spotted',
    'vaccinated' => 'no',
    'dewormed' => 'yes',
    'age' => 3,
    'type' => 'Cat',
    'image' => 'assets/images/adopt2.jpeg',
    'image2' => 'assets/images/cat2.jpeg',
    'image3' => 'assets/images/cat3.jpeg'
  ],
  [
    'ID' => 'HPH-A-119',
    'name' => 'Molly',
    'breed' => 'Bengal',
    'gender' => 'female',
    'color' => 'spotted',
    'vaccinated' => 'no',
    'dewormed' => 'yes',
    'age' => 3,
    'type' => 'Rabbit',
    'image' => 'assets/images/adopt5.jpeg',
    'image2' => 'assets/images/rabbit2.jpeg',
    'image3' => 'assets/images/rabbit3.jpeg'
  ]
];
?>